package com.origonetworks.isv.backend.integration.remote.type;

public enum EventType {
	SUBSCRIPTION_ORDER,
	SUBSCRIPTION_CHANGE,
	SUBSCRIPTION_CANCEL,
	SUBSCRIPTION_NOTICE,
	USER_ASSIGNMENT,
	USER_UNASSIGNMENT,
	USER_SYNC,
	ACCOUNT_SYNC,
	ACCOUNT_UNSYNC;
}
